# Generated by Django 4.1.7 on 2023-06-05 08:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200, verbose_name='问题描述')),
                ('answer', models.CharField(max_length=200, verbose_name='正确答案')),
                ('choices', models.CharField(blank=True, max_length=200, verbose_name='选项信息')),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocabulary', models.CharField(max_length=50, verbose_name='单词')),
                ('chinese', models.CharField(max_length=50, verbose_name='中文释义')),
                ('sentence', models.CharField(max_length=100, verbose_name='例句')),
                ('chinese_sentence', models.CharField(max_length=100, verbose_name='例句翻译')),
                ('type', models.CharField(max_length=100, verbose_name='被哪些单词书包含')),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50, verbose_name='单词书名称')),
                ('code', models.CharField(max_length=10, verbose_name='单词书对应代码')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, verbose_name='词语')),
                ('translation', models.CharField(max_length=200, verbose_name='翻译')),
                ('language', models.CharField(choices=[('Chinese', '中文'), ('English', '英语')], max_length=30, verbose_name='语言')),
                ('save_day', models.DateField(default=datetime.date.today, verbose_name='保存时间')),
                ('last_day', models.DateField(default=datetime.date.today, verbose_name='上次时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabularies.vocabularybooks', verbose_name='单词书')),
            ],
        ),
        migrations.CreateModel(
            name='WordTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=20, verbose_name='学习的时间')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabularies.word', verbose_name='单词')),
            ],
        ),
        migrations.CreateModel(
            name='WordScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='得分')),
                ('times', models.IntegerField(default=1, verbose_name='次数')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabularies.word', verbose_name='单词')),
            ],
        ),
        migrations.AddConstraint(
            model_name='vocabulary',
            constraint=models.UniqueConstraint(fields=('vocabulary',), name='vocabulary'),
        ),
        migrations.AddField(
            model_name='question',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabularies.word', verbose_name='单词'),
        ),
        migrations.AddConstraint(
            model_name='wordtime',
            constraint=models.UniqueConstraint(fields=('word', 'time'), name='word_time'),
        ),
        migrations.AddConstraint(
            model_name='wordscore',
            constraint=models.UniqueConstraint(fields=('word', 'times'), name='word_times'),
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(fields=('word', 'language', 'book'), name='book_word'),
        ),
        migrations.AddConstraint(
            model_name='vocabularybooks',
            constraint=models.UniqueConstraint(fields=('user', 'code'), name='user_code'),
        ),
    ]
